voices:
  Sarah:
    ref: refs/Sarah.wav
    who:
    - s
    gender: F
  King Orwell Rose:
    ref: refs/King Orwell Rose.wav
    who:
    - ko
    gender: M
  Varga:
    ref: refs/Varga.wav
    who:
    - v
    - bsk
    gender: M
  Kate:
    ref: refs/Kate.wav
    who:
    - k
    gender: F
  Marion:
    ref: refs/Marion.wav
    who:
    - m
    gender: M
  Narrator:
    ref: refs/Narrator.wav
    who:
    - narrator
    gender: F
  Caleb:
    ref: refs/Caleb.wav
    who:
    - ca
    gender: M
  Captain Belmont:
    ref: refs/Captain Belmont.wav
    who:
    - cb
    gender: M
  Dalia:
    ref: refs/Dalia.wav
    who:
    - dalia
    gender: F
  Hassar:
    ref: refs/Hassar.wav
    who:
    - h
    gender: M
  Razaphel:
    ref: refs/Razaphel.wav
    who:
    - r
    gender: M
  Thomas:
    ref: refs/Thomas.wav
    who:
    - t
    gender: M
  Xanthippe:
    ref: refs/Xanthippe.wav
    who:
    - x
    gender: F
  Generic Female Mature:
    ref: refs/Generic Female Mature.wav
    who: []
    gender: F
  Generic Female Young:
    ref: refs/Generic Female Young.wav
    who: []
    gender: F
  Generic Male Mature:
    ref: refs/Generic Male Mature.wav
    who: []
    gender: M
  Generic Male Young:
    ref: refs/Generic Male Young.wav
    who: []
    gender: M
  Sigmund:
    ref: refs/Sigmund.wav
    who:
    - sig
    gender: M
  Alaric:
    ref: refs/Alaric.wav
    who:
    - al
    gender: M
  Albert:
    ref: refs/Albert.wav
    who:
    - alb
    gender: M
  Alfred:
    ref: refs/Alfred.wav
    who:
    - alf
    gender: M
  Atilla:
    ref: refs/Atilla.wav
    who:
    - a
    gender: M
  Carolyn:
    ref: refs/Carolyn_1.wav
    who:
    - c
    gender: F
  Cassius:
    ref: refs/Cassius.wav
    who:
    - cas
    gender: M
  Daemon:
    ref: refs/Daemon.wav
    who:
    - dae
    gender: M
  Duke Antonio:
    ref: refs/Duke Antonio_1.wav
    who:
    - ant
    gender: M
  Gilead:
    ref: refs/Gilead.wav
    who:
    - gil
    gender: M
  Jaeid:
    ref: refs/Jaeid.wav
    who:
    - j
    gender: M
  Kim:
    ref: refs/Kim.wav
    who:
    - kim
    gender: F
  Kravel:
    ref: refs/Kravel.wav
    who:
    - kr
    gender: M
  Marshal Edmond:
    ref: refs/Marshal Edmond_1.wav
    who:
    - edm
    gender: M
  Metis:
    ref: refs/Metis.wav
    who:
    - met
    gender: M
  Sakar:
    ref: refs/Sakar.wav
    who:
    - sak
    gender: M
  Samayra:
    ref: refs/Carolyn_1.wav
    who:
    - sa
    gender: F
  Vaelen:
    ref: refs/Vaelen.wav
    who:
    - vae
    gender: M
  Orc:
    ref: refs/Orc.wav
    who:
    - orc
    gender: M
  Woodland Spirit:
    ref: refs/Woodland Spirit.wav
    who:
    - wsp
    gender: M
