voices:
  Sarah:
    ref: refs/Sarah_3.wav
    who:
    - s
    gender: F
  King Orwell Rose:
    ref: refs/King Orwell Rose.wav
    who:
    - ko
    gender: M
  Varga:
    ref: refs/Varga.wav
    who:
    - v
    gender: M
  Kate:
    ref: refs/Kate.wav
    who:
    - k
    gender: F
  Marion:
    ref: refs/Marion.wav
    who:
    - m
    gender: F
  Narrator:
    ref: refs/Narrator.wav
    who:
    - narrator
    gender: F
  Caleb:
    ref: refs/Caleb.wav
    who:
    - ca
    gender: M
  Captain Belmont:
    ref: refs/Captain Belmont.wav
    who:
    - cb
    gender: M
  Dalia:
    ref: refs/Dalia.wav
    who:
    - dalia
    gender: F
  Hassar:
    ref: refs/Hassar.wav
    who:
    - h
    gender: M
  Razaphel:
    ref: refs/Razaphel.wav
    who:
    - r
    gender: M
  Thomas:
    ref: refs/Thomas.wav
    who:
    - t
    gender: M
  Xanthippe:
    ref: refs/Xanthippe.wav
    who:
    - x
    gender: M
  Generic Female Mature:
    ref: refs/Generic Female Mature.wav
    who: []
    gender: F
  Generic Female Young:
    ref: refs/Generic Female Young.wav
    who: []
    gender: F
  Generic Male Mature:
    ref: refs/Generic Male Mature.wav
    who: []
    gender: M
  Generic Male Young:
    ref: refs/Generic Male Young.wav
    who: []
    gender: M
