voices:
  Sarah:
    ref: voice_candidates/Sarah/Sarah.wav
    who:
    - s
    gender: F
  King Orwell Rose:
    ref: voice_candidates/King Orwell Rose/King Orwell Rose.wav
    who:
    - ko
    gender: M
  Varga:
    ref: voice_candidates/Varga/Varga.wav
    who:
    - v
    - bsk
    gender: M
  Kate:
    ref: voice_candidates/Kate/Kate.wav
    who:
    - k
    gender: F
  Marion:
    ref: voice_candidates/Marion/Marion.wav
    who:
    - m
    gender: M
  Narrator:
    ref: voice_candidates/Narrator/Narrator.wav
    who:
    - narrator
    gender: F
  Caleb:
    ref: voice_candidates/Caleb/Caleb.wav
    who:
    - ca
    gender: M
  Captain Belmont:
    ref: voice_candidates/Captain Belmont/Captain Belmont.wav
    who:
    - cb
    gender: M
  Dalia:
    ref: voice_candidates/Dalia/Dalia.wav
    who:
    - dalia
    gender: F
  Hassar:
    ref: voice_candidates/Hassar/Hassar.wav
    who:
    - h
    gender: M
  Razaphel:
    ref: voice_candidates/Razaphel/Razaphel.wav
    who:
    - r
    gender: M
  Thomas:
    ref: voice_candidates/Thomas/Thomas.wav
    who:
    - t
    gender: M
  Xanthippe:
    ref: voice_candidates/Xanthippe/Xanthippe.wav
    who:
    - x
    gender: F
  Generic Female Mature:
    ref: voice_candidates/Generic Female Mature/Generic Female Mature.wav
    who: []
    gender: F
  Generic Female Young:
    ref: voice_candidates/Generic Female Young/Generic Female Young.wav
    who: []
    gender: F
  Generic Male Mature:
    ref: voice_candidates/Generic Male Mature/Generic Male Mature.wav
    who: []
    gender: M
  Generic Male Young:
    ref: voice_candidates/Generic Male Young/Generic Male Young.wav
    who: []
    gender: M
  Sigmund:
    ref: voice_candidates/Sigmund/Sigmund.wav
    who:
    - sig
    gender: M
  Alaric:
    ref: voice_candidates/Alaric/Alaric.wav
    who:
    - al
    gender: M
  Albert:
    ref: voice_candidates/Albert/Albert.wav
    who:
    - alb
    gender: M
  Alfred:
    ref: voice_candidates/Alfred/Alfred.wav
    who:
    - alf
    gender: M
  Atilla:
    ref: voice_candidates/Atilla/Atilla.wav
    who:
    - a
    gender: M
  Carolyn:
    ref: voice_candidates/Carolyn/Carolyn.wav
    who:
    - c
    gender: F
  Cassius:
    ref: voice_candidates/Cassius/Cassius.wav
    who:
    - cas
    gender: M
  Daemon:
    ref: voice_candidates/Daemon/Daemon.wav
    who:
    - dae
    gender: M
  Duke Antonio:
    ref: voice_candidates/Duke Antonio/Duke Antonio.wav
    who:
    - ant
    gender: M
  Gilead:
    ref: voice_candidates/Gilead/Gilead.wav
    who:
    - gil
    gender: M
  Jaeid:
    ref: voice_candidates/Jaeid/Jaeid.wav
    who:
    - j
    gender: M
  Kim:
    ref: voice_candidates/Kim/Kim.wav
    who:
    - kim
    gender: F
  Kravel:
    ref: voice_candidates/Kravel/Kravel.wav
    who:
    - kr
    gender: M
  Marshal Edmond:
    ref: voice_candidates/Marshal Edmond/Marshal Edmond.wav
    who:
    - edm
    gender: M
  Metis:
    ref: voice_candidates/Metis/Metis.wav
    who:
    - met
    gender: M
  Sakar:
    ref: voice_candidates/Sakar/Sakar.wav
    who:
    - sak
    gender: M
  Samayra:
    ref: voice_candidates/Carolyn/Carolyn.wav
    who:
    - sa
    gender: F
  Vaelen:
    ref: voice_candidates/Vaelen/Vaelen.wav
    who:
    - vae
    gender: M
  Orc:
    ref: voice_candidates/Orc/Orc.wav
    who:
    - orc
    gender: M
  Woodland Spirit:
    ref: voice_candidates/Woodland Spirit/Woodland Spirit.wav
    who:
    - wsp
    gender: M
